function report = verify_manuscript_consistency()
%VERIFY_MANUSCRIPT_CONSISTENCY Check CSV-to-LaTeX claim consistency.
%   The verifier intentionally checks only headline values that are quoted
%   in the manuscript. A passing result is evidence that these values match
%   the latest tables; it is not a substitute for rerunning experiments.

    script_dir = fileparts(mfilename('fullpath'));
    addpath(fullfile(script_dir, 'utils'));
    latex_dir = fullfile(script_dir, '..', 'Latex');
    table_dir = fullfile(script_dir, 'table');
    main_text = fileread(fullfile(latex_dir, 'main.tex'));
    supplementary_text = fileread(fullfile(latex_dir, 'supplementary.tex'));
    appendix_text = fileread(fullfile(latex_dir, 'appendix.tex'));

    checks = strings(0, 1);
    evidence = strings(0, 1);

    convergence = readtable(fullfile(table_dir, ...
        'table5_1_convergence.csv'), TextType='string');
    fixed = convergence(convergence.N == 50 & ...
        convergence.Method == "Fixed-weight IT2", :);
    proposed = convergence(convergence.N == 50 & ...
        convergence.Method == "Proposed IT2-W-FBRI", :);
    require_single_row(fixed, 'N=50 fixed-weight convergence');
    require_single_row(proposed, 'N=50 proposed convergence');
    require_contains(main_text, sprintf('%.4f', fixed.FinalAvgPayoff), ...
        'fixed-weight terminal payoff');
    require_contains(main_text, sprintf('%.4f', proposed.FinalAvgPayoff), ...
        'proposed terminal payoff');
    % Iteration counts are carried by the R column of Table~\ref{tab:conv}
    % rather than restated in prose; check the method-to-R binding in the table.
    require_contains(main_text, sprintf('%s & %d', fixed.Method, fixed.Iterations), ...
        'fixed-weight iteration count (Table R column)');
    require_contains(main_text, sprintf('%s & %d', proposed.Method, proposed.Iterations), ...
        'proposed iteration count (Table R column)');
    checks(end + 1) = "Simulation I headline";
    evidence(end + 1) = sprintf('N=50 payoff %.4f/%.4f, R=%d/%d', ...
        fixed.FinalAvgPayoff, proposed.FinalAvgPayoff, ...
        fixed.Iterations, proposed.Iterations);

    scenario = readtable(fullfile(table_dir, ...
        'table5_6b_sota_scenarioB.csv'), TextType='string');
    scenario_raw = readtable(fullfile(table_dir, ...
        'table5_6b_sota_scenarioB_raw.csv'), TextType='string');
    for row = 1:height(scenario)
        require_contains(main_text, fmt_mean_ci_tex( ...
            scenario.ExpectedPayoffMean(row), ...
            scenario.ExpectedPayoffCI95(row)), ...
            scenario.Method(row) + " expected payoff");
        require_contains(main_text, fmt_mean_ci_tex( ...
            scenario.WorstCaseQ5Mean(row), ...
            scenario.WorstCaseQ5CI95(row)), ...
            scenario.Method(row) + " lower-tail payoff");
        require_contains(main_text, fmt_mean_ci_tex( ...
            scenario.CEGammaMean(row), scenario.CEGammaCI95(row)), ...
            scenario.Method(row) + " CE");
    end
    num_scenario_seeds = numel(unique(scenario_raw.Seed));
    require_contains(main_text, sprintf('%d seeds', num_scenario_seeds), ...
        'main-text Scenario-B seed count');
    checks(end + 1) = "Scenario B table";
    evidence(end + 1) = sprintf('%d methods, %d seeds', ...
        height(scenario), num_scenario_seeds);

    fuzzy = readtable(fullfile(table_dir, ...
        'table5_8_fuzzy_game_sota.csv'), TextType='string');
    fz = fuzzy(fuzzy.Method == "Proposed IT2-W-FBRI", :);
    require_single_row(fz, 'fuzzy-game SOTA proposed row');
    require_contains(main_text, sprintf('$%.3f$', fz.E_U), ...
        'Table IV proposed mean payoff');
    require_contains(main_text, sprintf('$\\mathbf{%.3f}$', fz.WC_Q5), ...
        'Table IV proposed lower-tail payoff');
    require_contains(main_text, sprintf('$\\mathbf{%.3f}$', fz.CE_055), ...
        'Table IV proposed CE');
    checks(end + 1) = "Fuzzy/interval-game table";
    evidence(end + 1) = sprintf('E=%.3f, WC=%.3f, CE=%.3f', ...
        fz.E_U, fz.WC_Q5, fz.CE_055);

    premise = readtable(fullfile(table_dir, ...
        'table5_3b_premise_diagnostics.csv'));
    require_single_row(premise, 'premise diagnostics');
    if premise.GlobalCertificate
        error('verify_manuscript_consistency:unexpectedGlobalClaim', ...
            'The numerical premise diagnostic must not claim a global certificate.');
    end
    require_contains(supplementary_text, 'no global basin-wide', ...
        'local-only premise boundary');
    require_contains(main_text, 'numerical error floor', ...
        'matched-slow-time inference boundary');
    checks(end + 1) = "Premise boundary";
    evidence(end + 1) = sprintf( ...
        'L_sigma=%.4f, global=%d', ...
        premise.L_sigma_local, premise.GlobalCertificate);

    % Scenario-B v2 (dispersed) headline: worst-case member vs specialized CVaR.
    upgrade = readtable(fullfile(table_dir, ...
        'table5_6k_proposed_upgrade.csv'), TextType='string');
    v2_new = upgrade(upgrade.Mode == "dispersed" & ...
        upgrade.Method == "Proposed-V2Deep", :);
    v2_cvar = upgrade(upgrade.Mode == "dispersed" & ...
        upgrade.Method == "CVaR-game", :);
    sel = v2_new(v2_new.SeedGroup == "main", :);
    held = v2_new(v2_new.SeedGroup == "holdout", :);
    require_contains(main_text, sprintf('%.4f$ selection versus $%.4f', ...
        mean(sel.CE_055), mean(held.CE_055)), ...
        'v2 selection/held-out CE statement');
    v2_new = sortrows(v2_new, 'Seed');
    v2_cvar = sortrows(v2_cvar, 'Seed');
    if ~isequal(v2_new.Seed, v2_cvar.Seed)
        error('verify_manuscript_consistency:v2SeedMismatch', ...
            'v2 paired rows must share identical seeds.');
    end
    require_contains(main_text, sprintf('$+%.4f$/$+%.4f$/$+%.4f$', ...
        mean(v2_new.ExpectedPayoff - v2_cvar.ExpectedPayoff), ...
        mean(v2_new.WorstCaseQ5 - v2_cvar.WorstCaseQ5), ...
        mean(v2_new.CE_055 - v2_cvar.CE_055)), ...
        'v2 paired differences vs CVaR');
    require_contains(supplementary_text, sprintf( ...
        '$\\mathbf{%.4f}$ & $\\mathbf{%.4f}$', ...
        mean(sel.CE_055), mean(held.CE_055)), ...
        'dispersed-table worst-case member row');
    checks(end + 1) = "Scenario B v2 headline";
    evidence(end + 1) = sprintf('CE sel/held %.4f/%.4f, dCE=+%.4f', ...
        mean(sel.CE_055), mean(held.CE_055), ...
        mean(v2_new.CE_055 - v2_cvar.CE_055));

    % Deep-annealing certificate quoted in the main-table footnote.
    v1_new = upgrade(upgrade.Mode == "concentrated" & ...
        upgrade.Method == "Proposed-V1Deep", :);
    eps_str = sprintf('%.1e', mean(v1_new.EpsNE));   % e.g. 2.8e-06
    eps_tex = sprintf('%s\\times10^{%d}', ...
        extractBefore(eps_str, 'e'), str2double(extractAfter(eps_str, 'e')));
    require_contains(main_text, eps_tex, 'annealed eps_NE certificate');
    checks(end + 1) = "Annealed certificate";
    evidence(end + 1) = sprintf('eps_NE=%s', eps_str);

    % Certified-regime anchor row in the main comparison table:
    % alpha=0.5 member of the scalar s=0 family grid at single lambda=0.15.
    family = readtable(fullfile(table_dir, ...
        'table5_6h_sota_family_alpha_raw.csv'), TextType='string');
    fam = family(family.Alpha == 0.5, :);
    fam_ce = 0.45 * fam.ExpectedPayoff + 0.55 * fam.WorstCaseQ5;
    require_contains(main_text, sprintf('%.4f\\pm%.4f', ...
        mean(fam.ExpectedPayoff), ci95_verify(fam.ExpectedPayoff)), ...
        'certified anchor expected payoff');
    require_contains(main_text, sprintf('%.4f\\pm%.4f', ...
        mean(fam.WorstCaseQ5), ci95_verify(fam.WorstCaseQ5)), ...
        'certified anchor lower-tail payoff');
    require_contains(main_text, sprintf('%.4f\\pm%.4f', ...
        mean(fam_ce), ci95_verify(fam_ce)), 'certified anchor CE');
    checks(end + 1) = "Certified anchor row";
    evidence(end + 1) = sprintf('E=%.4f, WC=%.4f, CE=%.4f, R=%.0f', ...
        mean(fam.ExpectedPayoff), mean(fam.WorstCaseQ5), ...
        mean(fam_ce), mean(fam.Rounds));

    % Heterogeneous-role variant: restricted feasible sets exercised in
    % Simulation I, multi-population vertex branch of Proposition 3(b).
    hetero = readtable(fullfile(table_dir, ...
        'table5_9_heterogeneous_roles.csv'), TextType='string');
    het = hetero(hetero.Variant == "Heterogeneous", :);
    require_single_row(het, 'heterogeneous variant row');
    if ~het.Converged || het.qHat >= het.qTh || het.RepMaxMargin >= 0
        error('verify_manuscript_consistency:heteroInvalid', ...
            'Heterogeneous variant must converge with q_hat<q_th and negative margins.');
    end
    require_contains(main_text, sprintf( ...
        'converges in $%d$ iterations', het.Rounds), ...
        'heterogeneous W-FBRI rounds');
    require_contains(main_text, sprintf('\\hat{q}=%.3f', het.qHat), ...
        'heterogeneous contraction rate');
    require_contains(main_text, sprintf('exploitability $%.3f$', ...
        het.EpsNE), 'heterogeneous exploitability');
    require_contains(main_text, sprintf('below $%.3f$', ...
        het.RepMaxMargin), 'heterogeneous invasion margin');
    checks(end + 1) = "Heterogeneous roles";
    evidence(end + 1) = sprintf('R=%d, q=%.3f, eps=%.3f, margin=%.4f', ...
        het.Rounds, het.qHat, het.EpsNE, het.RepMaxMargin);

    % Focused certified regime: closed-form radius-profile modulus of
    % Corollary 2 (C-28) and the certified/excluded focusing exponents.
    p_mod = config_params();
    theta0 = [0.40; 0.35; 0.25];
    [dt_rho, mod_info] = sec4_3_1_radius_profile_modulus(p_mod, theta0, 0.10);
    d_nu0 = sec4_3_1_kernel_variation_modulus(p_mod, theta0);
    kappa1 = mod_info.kappa_s(d_nu0, 0.9, 1, 0.15);
    kappa40 = mod_info.kappa_s(d_nu0, 0.5, 40, 0.15);
    if kappa1 >= 1 || kappa40 <= 1
        error('verify_manuscript_consistency:focusedRegime', ...
            'Focused regime must certify s=1 and exclude s=40.');
    end
    require_contains(main_text, sprintf( ...
        '\\widetilde D_{\\rho}=%.3f', dt_rho), 'radius-profile modulus');
    require_contains(main_text, sprintf( ...
        '\\kappa^{(1)}=%.2f<1', kappa1), 'focused certified kappa');
    checks(end + 1) = "Focused certified regime";
    evidence(end + 1) = sprintf('Dt_rho=%.3f, k1=%.2f, k40=%.1f', ...
        dt_rho, kappa1, kappa40);

    forbidden = [ ...
        "g(\\sum_j\\pi_{i,j}\\mu_{k,i,j}) defines the game"; ...
        "directly verifies the matched slow-time scaling"; ...
        "joint Lyapunov descent trajectories"; ...
        "IoV-aligned, mildly tail-leaning"; ...
        "E[U]="; ...
        "0.7717\pm"; ...
        "0.7740\pm"; ...
        "matches the specialized CVaR-game solution"];
    combined = string(main_text) + newline + ...
        string(supplementary_text) + newline + string(appendix_text);
    for idx = 1:numel(forbidden)
        if contains(combined, forbidden(idx))
            error('verify_manuscript_consistency:staleClaim', ...
                'Stale or forbidden claim remains: %s', forbidden(idx));
        end
    end
    checks(end + 1) = "Stale-claim sweep";
    evidence(end + 1) = sprintf('%d forbidden phrases absent', ...
        numel(forbidden));

    report = table(checks(:), repmat("PASS", numel(checks), 1), ...
        evidence(:), 'VariableNames', {'Check','Status','Evidence'});
    writetable(report, fullfile(table_dir, ...
        'manuscript_consistency_manifest.csv'));
    disp(report);
end

function require_single_row(table_value, label)
    if height(table_value) ~= 1
        error('verify_manuscript_consistency:rowCount', ...
            '%s must resolve to exactly one row.', label);
    end
end

function require_contains(text, needle, label)
    if ~contains(text, needle)
        error('verify_manuscript_consistency:missingValue', ...
            'Manuscript is missing %s: %s', label, needle);
    end
end

function s = fmt_mean_ci_tex(m, c)
% 均值±CI 的正文需求串; CI 在 %.4f 下舍入为 0 时改用 1 位有效数字科学计数
    if c > 0 && round(c, 4) == 0
        e = sprintf('%.0e', c);   % e.g. '5e-05'
        s = sprintf('%.4f\\pm%s\\times10^{%d}', m, ...
            extractBefore(e, 'e'), str2double(extractAfter(e, 'e')));
    else
        s = sprintf('%.4f\\pm%.4f', m, c);
    end
end

function c = ci95_verify(x)
    x = x(~isnan(x));
    n = numel(x);
    if n <= 1
        c = 0;
        return
    end
    degrees_freedom = n - 1;
    t_critical = sqrt(degrees_freedom * ...
        (1 / betaincinv(0.05, degrees_freedom / 2, 0.5) - 1));
    c = t_critical * std(x) / sqrt(n);
end
